name: Validate Packer file

on:
  push:
    branches: [test]

jobs:
  validate-packer-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.2/packer_1.7.2_linux_amd64.zip
          unzip packer_1.7.2_linux_amd64.zip
          chmod +x packer
          sudo mv packer /usr/local/bin/
          packer version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      

      - name: Run Packer pulgin installation
        run: packer init .

      - name: create and configure
        run: |
          touch .env
          echo port=${{ secrets.PORT }} >> .env
          echo host=${{ secrets.HOSTIP }} >> .env
          echo dialect=${{ secrets.DIALECT }} >> .env
          echo user=${{ secrets.USER }} >> .env
          echo password=${{ secrets.PASSWORD }}>> .env
          echo database=${{ secrets.DATABASE }} >> .env

      - name: zip all files
        run: zip -r webapp.zip .

      - name: Build ami with packer
        run: packer build aws-debian.pkr.hcl
        env:
          MARIADB_PASSWORD: ${{ secrets.PASSWORD }}
          MYSQL_DB_NAME: ${{  secrets.DATABASE  }}
          MARIADB_USER: ${{ secrets.USER }}
          AWS_AMI_REGION: ${{ secrets.AWS_REGION }}

